export const BATH_PATH='http://localhost:8080/basic-webapp/superadmin'
export const IMAGE_PATH = 'http://localhost:8080/basic-webapp/superadmin/'
export const HEADLINE_GET_PATH = '/listheadlines'
export const HEADLINE_ADD_PATH = '/addheadline'
export const HEADLINE_EDIT_PATH = '/modifyheadline'
export const HEADLINE_DELETE_PATH = '/removeheadline'
export const HEADLINE_BATCH_DELETE_PATH='/removeheadlines'